import icon from '../../assets/icons/USA.png'

 const data = [
    {
        id : 1,
        rate:"3.3.0(14/05/2018)",
        status: "New",
        image : icon,
        name:"Kevin Joe",
        text:"File system changed from Dokan to CBFS Host.Cloud Drive is now a network drive Various bug Fires and stability improvements Share permissions re-design and optimization",
        backGroundColor : "green",
        link:"Download",
    },
    {
        id : 2,
        rate:"3.1.0(20/05/2015)",
        status: "Fix",
        image : icon,
        name:"Kevin Joe",
        backGroundColor : "blue",
        text:"Introducing Host Cloud Drive - virtual drive functionallity New snare options and management Nev more user friendly design Syne optimizations Various performance improvements and bug fixes",
        link:"Download",
    },
    {
        id : 3,
        rate:"3.1.0(20/05/2015)",
        status: "Improvement",
        image: icon,
        backGroundColor : "violet",
        name:"Kevin Joe",
        text:"Added Settings for Auto Start Added lipo ale Notification Sored Ootimization Bug Fixes",
        link:"Download",
    },
    {
        id : 4,
        rate:"3.3.0(14/05/2018)",
        status: "New",
        image : icon,
        name:"Kevin Joe",
        text:"File system changed from Dokan to CBFS Host.Cloud Drive is now a network drive Various bug Fires and stability improvements Share permissions re-design and optimization",
        backGroundColor : "green",
        link:"Download",
    },
    {
        id : 5,
        rate:"3.1.0(20/05/2015)",
        status: "Fix",
        image : icon,
        name:"Kevin Joe",
        backGroundColor : "blue",
        text:"Introducing Host Cloud Drive - virtual drive functionallity New snare options and management Nev more user friendly design Syne optimizations Various performance improvements and bug fixes",
        link:"Download",
    },
    {
        id : 6,
        rate:"3.1.0(20/05/2015)",
        status: "Improvement",
        image: icon,
        backGroundColor : "violet",
        name:"Kevin Joe",
        text:"Added Settings for Auto Start Added lipo ale Notification Sored Ootimization Bug Fixes",
        link:"Download",
    },
    {
        id : 7,
        rate:"3.3.0(14/05/2018)",
        status: "New",
        image : icon,
        name:"Kevin Joe",
        text:"File system changed from Dokan to CBFS Host.Cloud Drive is now a network drive Various bug Fires and stability improvements Share permissions re-design and optimization",
        backGroundColor : "green",
        link:"Download",
    },
    {
        id : 8,
        rate:"3.1.0(20/05/2015)",
        status: "Fix",
        image : icon,
        name:"Kevin Joe",
        backGroundColor : "blue",
        text:"Introducing Host Cloud Drive - virtual drive functionallity New snare options and management Nev more user friendly design Syne optimizations Various performance improvements and bug fixes",
        link:"Download",
    },
    {
        id : 9,
        rate:"3.1.0(20/05/2015)",
        status: "Improvement",
        image: icon,
        backGroundColor : "violet",
        name:"Kevin Joe",
        text:"Added Settings for Auto Start Added lipo ale Notification Sored Ootimization Bug Fixes",
        link:"Download",
    },

]

export default data;
